// Important: DO NOT EDIT THIS FILE!

import data from "../data/AnOrdBez.json";

export interface AnOrdBez {
  id: number;
  quelleId: number;
  quelleElement: string;
  zielId: number;
  zielElement: string;
  typ: string;
  abstand: number;
  abstandExakt: boolean;
}

export const anOrdBezService = {
  getAll: async (): Promise<AnOrdBez[]> => {
    return new Promise((resolve) => {
      setTimeout(() => resolve(data as AnOrdBez[]), 100);
    });
  },

  getById: async (id: number): Promise<AnOrdBez | undefined> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const item = data.find((item) => item.id === id);
        resolve(item as AnOrdBez | undefined);
      }, 100);
    });
  },
};
