// Important: DO NOT EDIT THIS FILE!

import data from "../data/Bestellung.json";

export interface Bestellung {
  id: number;
  materialId: number;
  verfuegbarTag: number;
  menge: number;
  fix: boolean;
}

export const bestellungService = {
  getAll: async (): Promise<Bestellung[]> => {
    return new Promise((resolve) => {
      setTimeout(() => resolve(data as Bestellung[]), 100);
    });
  },

  getById: async (id: number): Promise<Bestellung | undefined> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const item = data.find((item) => item.id === id);
        resolve(item as Bestellung | undefined);
      }, 100);
    });
  },

  getByMaterial: async (materialId: number): Promise<Bestellung[]> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const items = data.filter((item) => item.materialId === materialId);
        resolve(items as Bestellung[]);
      }, 100);
    });
  },
};
