// Important: DO NOT EDIT THIS FILE!

import data from "../data/MaterialErzeugung.json";

export interface MaterialErzeugung {
  fertObjektId: number;
  materialId: number;
  menge: number;
}

export const materialErzeugungService = {
  getAll: async (): Promise<MaterialErzeugung[]> => {
    return new Promise((resolve) => {
      setTimeout(() => resolve(data as MaterialErzeugung[]), 100);
    });
  },

  getByFertObjekt: async (
    fertObjektId: number
  ): Promise<MaterialErzeugung[]> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const items = data.filter((item) => item.fertObjektId === fertObjektId);
        resolve(items as MaterialErzeugung[]);
      }, 100);
    });
  },

  getByMaterial: async (materialId: number): Promise<MaterialErzeugung[]> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const items = data.filter((item) => item.materialId === materialId);
        resolve(items as MaterialErzeugung[]);
      }, 100);
    });
  },
};
