// Important: DO NOT EDIT THIS FILE!

import data from "../data/MitarbeiterEignung.json";

export interface MitarbeiterEignung {
  ressourceId: number;
  mitarbeiterId: number;
  eignung: number;
}

export const mitarbeiterEignungService = {
  getAll: async (): Promise<MitarbeiterEignung[]> => {
    return new Promise((resolve) => {
      setTimeout(() => resolve(data as MitarbeiterEignung[]), 100);
    });
  },

  getByMitarbeiterAndRessource: async (
    mitarbeiterId: number,
    ressourceId: number
  ): Promise<MitarbeiterEignung | undefined> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const item = data.find(
          (item) =>
            item.mitarbeiterId === mitarbeiterId &&
            item.ressourceId === ressourceId
        );
        resolve(item as MitarbeiterEignung | undefined);
      }, 100);
    });
  },

  getByMitarbeiter: async (
    mitarbeiterId: number
  ): Promise<MitarbeiterEignung[]> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const items = data.filter(
          (item) => item.mitarbeiterId === mitarbeiterId
        );
        resolve(items as MitarbeiterEignung[]);
      }, 100);
    });
  },

  getByRessource: async (
    ressourceId: number
  ): Promise<MitarbeiterEignung[]> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const items = data.filter((item) => item.ressourceId === ressourceId);
        resolve(items as MitarbeiterEignung[]);
      }, 100);
    });
  },
};
